%YAML 1.2
---
device: 1

dataset:
    input_train: /datadrive/mmaps/train_grouped/
    input_test: /datadrive/mmaps/test_grouped/

training:
    lr_intial: 0.0001
    lr_gamma: 0.1
    lr_steps:
        - 100000
        - 1000000
        - 1300000
    batch_size: 200
    test_steps: 2000
    total_steps: 1400000
    test_size: 200

model:
    type: leela
    outputs:
        - is_blunder_mean
    channels: 64
    blocks: 6
...
